name: Test
on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: yarn
          node-version: 16
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Check dependencies deduplicated
        run: yarn run yarn-deduplicate --fail
      - name: Build
        run: yarn run build
      - name: Format
        run: yarn run prettier --check
      - name: Lint
        run: yarn run xo
      - name: Test
        run: yarn run test
